name: mu-editor
version: 1.0.0
summary: A simple Python code editor
description: |
    Mu is a simple code editor for beginner programmers based on extensive
    feedback from teachers and learners. Having said that, Mu is for anyone who
    wants to use a simple “no frills” editor.

grade: devel
confinement: devmode

apps:
    mu-editor:
        command: desktop-launch mu-editor
        plugs: [home, network, gsettings, desktop, desktop-legacy, wayland, unity7, pulseaudio]

parts:
    mu-editor:
        after: [desktop-qt5]
        plugin: python
        python-version: python3
        source: .
        stage-packages:
            - python3-pyqt5
            - python3-pyqt5.qsci
            - python3-pyqt5.qtsvg
            - python3-pyqt5.qtserialport
            - python3-serial
            - python3-appdirs
            - python3-semver
